# NYMPY

- É uma das principais libs de computação científica.

## Numpy Matriz(array)

In [2]:
# Importar a lib Numpy
import numpy as np


In [3]:
meusNumeros = np.array([1,2,3,4,5,6,7,8,9])
print(meusNumeros)
print(type(meusNumeros))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
# Criando uma matriz com números inteiros e flutuantes(Com casas decimais)
meusNumerosDois = np.array([
    [1.2, 2, 3.6],
    [5.1, 3, 1]
])

print(meusNumerosDois)

[[1.2 2.  3.6]
 [5.1 3.  1. ]]


In [5]:
# Criando Matrizes com 0s e 1s

zeros = np.zeros((5, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
ones = np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


*texto em itálico*### Arange e Shape

In [7]:
# Arange vai criar uma listagem no intervalo indicado
# Nesse caso, do 0 até o 8
meusDados = np.arange(9)
print(meusDados)

[0 1 2 3 4 5 6 7 8]


In [8]:
# Reshape vai mudar o formato da minha matriz.
# Nesse exemplo, mudados para uma Matriz bidimensional de 3 linhas x 3 colunas
meusDados = np.arange(9).reshape(3,3)
print(meusDados)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Fatiando(Slicing) de uma Matriz

In [9]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
print(numbers)

[1 2 3 4 5 6 7 8 9]


In [10]:
print(numbers[2:5])

[3 4 5]


In [11]:
print(numbers[:-5])

[1 2 3 4]


In [12]:
print(numbers[5:])

[6 7 8 9]


In [13]:
print(numbers[::-1])

[9 8 7 6 5 4 3 2 1]


In [14]:
print(numbers[::-2])

[9 7 5 3 1]


In [15]:
print(numbers[::-3])


[9 6 3]
