# Numpy

Biblioteca do python para trabalhar com números, principalmente.

In [1]:
# importando a lib

import numpy as np

In [2]:
# Array é basicamente um vetor, podemos considera-lo uma lista também

a = np.array ([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
# Mostrar qual o tipo(type) dos dados que tenho em 'a'

print(type(a))

<class 'numpy.ndarray'>


# Criando uma MATRIZ

Arrays são unidimesionais, ou seja, uma unica linha, já matrizes são bidimensionais, oned temos linhas e colunas. 

In [4]:
# Vamos criar uma matriz de Nº inteiros 

b = np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[1,2,3,4,5,6],[7,8,9,4,5,6],[3,2,1,6,5,4]])
print(c)

[[1 2 3 4 5 6]
 [7 8 9 4 5 6]
 [3 2 1 6 5 4]]


In [6]:
# Matriz com decimal

d = np.array([[1.2,3,4,5,6],[7.8,9,4,5,6],[3.2,1,6,5,4]])
print(d)

[[1.2 3.  4.  5.  6. ]
 [7.8 9.  4.  5.  6. ]
 [3.2 1.  6.  5.  4. ]]


In [7]:
# Matriz com decimal

d = np.array([[1.2,3,4,5,6],[7.8,9,4.5,6],[3.2,1,6,5,4]])
print(d)

[list([1.2, 3, 4, 5, 6]) list([7.8, 9, 4.5, 6]) list([3.2, 1, 6, 5, 4])]


C:\Users\caiol\AppData\Local\Temp/ipykernel_28448/3561276411.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.array([[1.2,3,4,5,6],[7.8,9,4.5,6],[3.2,1,6,5,4]])


In [8]:
# Zeros e um
# np.zerros(linhas, colunas)

zeros = np.zeros((3,5))

print(zeros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
um = np.ones((3,5))

print(um)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Arange, Shape e Reshape

In [10]:
# Arange , iremos criar em um range definido por nós, uma sequencia de 0 a 10

minhaMatriz = np.arange(11)

# mostrar o resultado que foi gerado 

print('Minha Matriz possui: ', minhaMatriz)

Minha Matriz possui:  [ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
minhaMatriz = np.arange(12) # mudando para 12

print('Minha Matriz possui: ', minhaMatriz) 
print('\n')      
minhaMatriz = np.arange(12).reshape(3,4)

print('Minha Matriz modificada com o reshape: \n', minhaMatriz)

Minha Matriz possui:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


Minha Matriz modificada com o reshape: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# EXERCÍCIO MATRIZ

1. Quero uma matriz onde armazene de 0 a 50;
2. Crie uma matriz que receba 24 números, utilizando o reshape, faça com que os valores venham aleatoriamente - 6L e 4C;
3. crie um array com 4 posições.

In [12]:
# Arange , iremos criar em um range definido por nós, uma sequencia de 0 a 50

minhaMatrizEX = np.arange(51)

# mostrar o resultado que foi gerado 

print('Minha Matriz possui: ', minhaMatrizEX)

Minha Matriz possui:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [13]:
minhaMatrizEX = np.arange(25) # mudando para 12

print('Minha Matriz possui: ', minhaMatrizEX) 
print('\n')      
minhaMatrizEX = np.arange(25).reshape(5,5)

print('Minha Matriz modificada com o reshape: \n', minhaMatrizEX)

Minha Matriz possui:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


Minha Matriz modificada com o reshape: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
# Na verdade precisa somente desta etapa:

minhaMatrizEX = np.arange(25).reshape(5,5)

print('Minha Matriz modificada com o reshape: \n', minhaMatrizEX)

Minha Matriz modificada com o reshape: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
# array com 4 posições 

quatro = np.arange(4)

print(quatro)

[0 1 2 3]


# Slice (Fatiando as minhas matrizes)

In [16]:
numeros  = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(numeros)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [17]:
print(numeros[2:6])

[2 3 4 5]


In [18]:
print(numeros[5]) # até o quinto

5


In [19]:
print(numeros[:5])

[0 1 2 3 4]


In [20]:
print(numeros[:-5]) # -5 dos últimos

[ 0  1  2  3  4  5  6  7  8  9 10]


In [21]:
print(numeros[:-3]) # -3 dos últimos

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
print(numeros[3:-3]) # -3 dos últimos e primeiros 

[ 3  4  5  6  7  8  9 10 11 12]


In [23]:
# imprimindo todos os valores 

print(numeros)
print(numeros[::])
print(numeros[:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [24]:
# imprimindo de forma inversa 

print(numeros[::-1])
print(numeros[::-2])

print(len(numeros))

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[15 13 11  9  7  5  3  1]
16


In [25]:
print(numeros)
print(numeros[0])
print(numeros[1])
print(numeros[2])
print(numeros[3])
print(numeros[4])
print(numeros[5])
print(numeros[6])
print(numeros[7])
print(numeros[8])
print(numeros[9])
print(numeros[10])
print(numeros[11])
print(numeros[12])
print(numeros[13])
print(numeros[14])
print(numeros[15])

# vai até o 15, somente, se colocar a mais da erro, pois ele conta o "0", basta considerar 1 a menos da contagem total de "Len",
# por isso vamos  até o 15

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [26]:
cem = np.arange(100)
print(cem)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [27]:
print(cem[::5])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


# EX. 2 

- Vetor com 50 Nº; 
- impressão de 5 em 5 e 2 em 2;
- valores inversos

In [28]:
cinquenta = np.arange(51)

print(cinquenta)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [29]:
print(cinquenta[::5])

[ 0  5 10 15 20 25 30 35 40 45 50]


In [30]:
print(cinquenta[::2])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


In [31]:
print(cinquenta[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]
